language: node_js
sudo: true
dist: trusty
cache:
  directories:
    - node_modules

node_js:
  - '6.9.1'

branches:
  except:
  - gh-pages

before_install:

script:
  - npm test
  - npm run build

after_success:
  # Send coverage data to Coveralls
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js


after_script:
